name: Build and publish

on:
  push:
    branches: [main]
    tags:
      - v*.*.*
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
      - run: yarn
      - run: yarn build
      - working-directory: build
        run: zip -r dog.clockwork.obs.zip dog.clockwork.obs
      - uses: actions/upload-artifact@v1
        with:
          name: dog.clockwork.obs.zip
          path: build/dog.clockwork.obs.zip
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          allowUpdates: true
          artifacts: build/dog.clockwork.obs.zip
          token: ${{ secrets.GITHUB_TOKEN }}
